export default [
  { code: "AK", name: "Alabama" },
  { code: "AL", name: "Alaska" },
  { code: "AR", name: "Arizona" },
  { code: "AZ", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "IA", name: "Idaho" },
  { code: "ID", name: "Illinois" },
  { code: "IL", name: "Indiana" },
  { code: "IN", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "MA", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "ME", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MO", name: "Mississippi" },
  { code: "MS", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NC", name: "Nebraska" },
  { code: "ND", name: "Nevada" },
  { code: "NE", name: "New Hampshire" },
  { code: "NH", name: "New Jersey" },
  { code: "NJ", name: "New Mexico" },
  { code: "NM", name: "New York" },
  { code: "NV", name: "North Carolina" },
  { code: "NY", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VA", name: "Vermont" },
  { code: "VT", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WI", name: "West Virginia" },
  { code: "WV", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];
